version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=EGD\SQLEXPRESS;Database=TrackingDb;User=sa;Password=1234;TrustServerCertificate=True
      - ConnectionStrings__HangfireConnection=Server=EGD\SQLEXPRESS;Database=TrackingHangfireDb;User=sa;Password=1234;TrustServerCertificate=True

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1234
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql

volumes:
  sqldata: